
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter} from "next/font/google";
import { Providers } from "./lib/provider";



const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <Providers>
            
            {children}
        </Providers>
          

        
      </body>
    </html>
  );
}