"use client";

import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";


const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

      <body className={`${inter.variable} antialiased`}>

          <Header />
          <div className="h-[calc(100vh-3.5rem)] grid grid-cols-[17rem_auto]">
            <Sidebar />
            {children}
          </div>

      </body>

  );
}
